baseURL       = "https://ulawi.org/"
languageCode  = "de-de"
title         = "Ulawi e.V. | Urbane Permakultur"
theme         = "roxo-hugo."
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Über uns"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Aktivitäten"
    url     = "portfolio"
    weight  = 3
 # [[menu.nav]]
  #  name    = "Blog"
  #  url     = "blog"
  #  weight  = 4
  #[[menu.nav]]
   # name    = "Kontakt"
   # url     = "contact"
   # weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Ulawi e.V. | Gemeischaftlich Permakultur leben"
  author = "Ulawi e.V."
  # Google Analitycs
  #googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
 # fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Vorname"
    placeholder_last_name         = "Nachname"
    placeholder_email             = "Email"
    placeholder_project_type      = "Worum geht's?"
    placeholder_about_the_project = "Deine freundliche Nachricht an uns"
    send_message                  = "Abschicken"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = false
    name    = "Kontakt"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/2562x1440joshua-lanzarini-Vct0oBHNmv4-unsplash.jpg"
    heading               = "Wir sind ein Verein für urbane Landwirtschaft und Permakultur"
    tagline               = "WIR ENTEN, WAS WIR SÄEN"
    primary_button        = "Unsere Aktivitäten"
    primary_button_url    = "portfolio"
    secondary_button      = "Kontakt"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "UNSERE AKTIVITÄTEN"
    subtitle  = "Beobachten, experimentieren, langfristig stabile, widerstandsfähige und gerecht verteilte Lebensräume schaffen."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LASS UNS ZUSAMMEN WACHSEN"
   # primary_button      = "Anfrage senden"
    #primary_button_url  = "contact"
    #secondary_button    = "Not Convinced"
    #secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Kontaktinfo"
      address = "Hinter dem Bach, Osterholz-Scharmbeck"
      #phone   = "409-896-1444"
      email   = "kontakt@ulawi.org"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Über uns"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Aktivitäten"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Impressum"
          url  = "blog/impressum"
      # Footer Social Media
      [params.footer.social]
        title   = "Wir sind lieber draußen als auf Social Media "
      #  [[params.footer.social.link]]
       #   name = "Medium"
        #  url  = "#"
       # [[params.footer.social.link]]
        #  name = "Behance"
        #  url  = "#"
       # [[params.footer.social.link]]
        #  name = "Dribbble"
        #  url  = "#"
       # [[params.footer.social.link]]
       #   name = "Instagram"
       #   url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Wir leben Permakultur."
        description = "Beobachten, experimentieren, langfristig stabile, widerstandsfähige und gerecht verteilte Lebensräume schaffen."
